# python version 1.0						DO NOT EDIT
#
# This python file has been generated by smidump version 0.5.0:
#
#   smidump -f python MY-MIB

FILENAME = "MY-MIB.txt"

MIB = {
    "moduleName" : "MY-MIB",

    "MY-MIB" : {
        "nodetype" : "module",
        "language" : "SMIv2",
        "organization" :    
            """MyOrganization""",
        "contact" : 
            """email@example.com""",
        "description" :
            """MIB for custom SNMP agent""",
        "revisions" : (
            {
                "date" : "2024-01-26 00:00",
                "description" :
                    """This custom version MIB""",
            },
        ),
        "identity node" : "myMIB",
    },

    "imports" : (
        {"module" : "SNMPv2-SMI", "name" : "MODULE-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "OBJECT-TYPE"},
        {"module" : "SNMPv2-SMI", "name" : "Integer32"},
    ),

    "nodes" : {
        "enterprises" : {
            "nodetype" : "node",
            "moduleName" : "MY-MIB",
            "oid" : "1.3.6.1.4.1",
        }, # node
        "myMIB" : {
            "nodetype" : "node",
            "moduleName" : "MY-MIB",
            "oid" : "1.3.6.1.4.1.9999",
            "status" : "current",
        }, # node
        "memoryUtil" : {
            "nodetype" : "scalar",
            "moduleName" : "MY-MIB",
            "oid" : "1.3.6.1.4.1.9999.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """Memory Utilization in percentage""",
        }, # scalar
        "cpuUtil" : {
            "nodetype" : "scalar",
            "moduleName" : "MY-MIB",
            "oid" : "1.3.6.1.4.1.9999.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """CPU Utilization in percentage""",
        }, # scalar
        "diskUtil" : {
            "nodetype" : "scalar",
            "moduleName" : "MY-MIB",
            "oid" : "1.3.6.1.4.1.9999.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """Disk Utilization in percentage""",
        }, # scalar
    }, # nodes

}
